# Generated by Django 4.1.2 on 2023-01-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True, unique=True, verbose_name='number phone'),
        ),
    ]
